const fs = require('fs');
const t = JSON.parse(fs.readFileSync('./public/locales/translations.json', 'utf8'));

function deepApply(obj, dict) {
    if (!obj || typeof obj !== 'object' || Array.isArray(obj)) {
        return typeof obj === 'string' && dict.hasOwnProperty(obj) ? dict[obj] : obj;
    }
    const result = {};
    for (const key in obj) {
        result[key] = deepApply(obj[key], dict);
    }
    return result;
}

// COMPLETE FINAL DICTIONARIES - ALL REMAINING VALUES
const complete = {
    de: {
        "translations@baobabhope.org": "translations@baobabhope.org",
        "your.email@organization.com": "ihre.email@organisation.de",
        "2025-01-27T12:30:00.000Z": "2025-01-27T12:30:00.000Z",
        "https://your-website.com": "https://ihre-webseite.de",
        "Minimum donation is $5": "Mindestspende beträgt 5$",
        "https://baobabhope.org": "https://baobabhope.org",
        "info@baobabhope.org": "info@baobabhope.org",
        "1234 5678 9012 3456": "1234 5678 9012 3456",
        "$50,000 - $100,000": "50.000$ - 100.000$",
        "$10,000 - $50,000": "10.000$ - 50.000$",
        "+1 (555) 123-4567": "+1 (555) 123-4567",
        "Under $10,000": "Unter 10.000$",
        "Over $100,000": "Über 100.000$",
        "index, follow": "index, follow",
        "Last updated": "Zuletzt aktualisiert",
        "Apply Filters": "Filter anwenden",
        "Upload failed": "Upload fehlgeschlagen",
        "Retry Upload": "Upload wiederholen",
        "Uploading...": "Wird hochgeladen...",
        "Contact Info": "Kontaktinfo",
        "Marie Kouadio": "Marie Kouadio",
        "Jean-Baptiste Dubois": "Jean-Baptiste Dubois",
        "Your full name": "Ihr vollständiger Name",
        "Your job title": "Ihre Berufsbezeichnung",
        "Error occurred": "Fehler aufgetreten",
        "File too large": "Datei zu groß",
        "Goal achieved": "Ziel erreicht",
        "What Drives Us": "Was uns antreibt",
        "Learn Our Story": "Erfahren Sie unsere Geschichte",
        "Our Focus Areas": "Unsere Schwerpunktbereiche",
        "Our Core Values": "Unsere Grundwerte",
        "Community First": "Gemeinschaft zuerst",
        "Drop files here": "Dateien hier ablegen",
        "Partnership Type": "Partnerschaftstyp",
        "In-kind Donation": "Sachspende",
        "About BAOBAB HOPE": "Über BAOBAB HOPE",
        "Lives Transformed": "Transformierte Leben",
        "Countries Reached": "Erreichte Länder",
        "Support Education": "Bildung unterstützen",
        "Copy to clipboard": "In Zwischenablage kopieren",
        "Invalid file type": "Ungültiger Dateityp",
        "Maximum file size": "Maximale Dateigröße",
        "Upload successful": "Upload erfolgreich",
        "Event Partnership": "Veranstaltungspartnerschaft",
        "Financial Support": "Finanzielle Unterstützung",
        "Preferred Schedule": "Bevorzugter Zeitplan",
        "Community Wellness": "Gemeinschaftswohlbefinden",
        "Our Impact Stories": "Unsere Wirkungsgeschichten",
        "Our Growing Impact": "Unsere wachsende Wirkung",
        "Support Healthcare": "Gesundheitsversorgung unterstützen",
        "Healthcare for All": "Gesundheitsversorgung für alle",
        "Your email address": "Ihre E-Mail-Adresse",
        "Allowed file types": "Zulässige Dateitypen",
        "Support Environment": "Umwelt unterstützen",
        "Partnership Details": "Partnerschaftsdetails",
        "Something went wrong": "Etwas ist schief gelaufen",
        "View Health Projects": "Gesundheitsprojekte ansehen",
        "Clean Water for Life": "Sauberes Wasser fürs Leben",
        "All rights reserved.": "Alle Rechte vorbehalten.",
        "Protecting Our Planet": "Unseren Planeten schützen",
        "Strategic Partnership": "Strategische Partnerschaft",
        "Employee Volunteering": "Mitarbeiterfreiwilligendienst",
        "Learn About Our Impact": "Erfahren Sie mehr über unsere Wirkung",
        "Support Water Projects": "Wasserprojekte unterstützen",
        "Your organization name": "Ihr Organisationsname",
        "Please enter your organization name": "Bitte geben Sie Ihren Organisationsnamen ein",
        "Please enter a valid website URL": "Bitte geben Sie eine gültige Website-URL ein",
        "Building Sustainable Water Systems": "Nachhaltige Wassersysteme aufbauen",
        "Empowering Through Education": "Stärkung durch Bildung",
        "Ready to Plant Seeds of Change?": "Bereit, Samen des Wandels zu pflanzen?",
        "Please enter your job title": "Bitte geben Sie Ihre Berufsbezeichnung ein",
        "Growing Together Since 2020": "Gemeinsam wachsen seit 2020",
        "Education Transforms Lives": "Bildung transformiert Leben",
        "Building Brighter Futures": "Hellere Zukünfte aufbauen",
        "Bringing Medical Care to Those in Need": "Medizinische Versorgung zu Bedürftigen bringen",
        "Building Brighter Futures Through Learning": "Hellere Zukünfte durch Lernen aufbauen",
        "Environmental Conservation for Future Generations": "Umweltschutz für zukünftige Generationen",
        "Stay informed about our latest actions and impact": "Bleiben Sie informiert über unsere neuesten Aktionen und Wirkung",
        "Started with a vision to create sustainable change": "Begonnen mit einer Vision, nachhaltigen Wandel zu schaffen",
        "Growing hope, nurturing communities, creating sustainable futures.": "Hoffnung wachsen lassen, Gemeinschaften pflegen, nachhaltige Zukünfte schaffen.",
        "From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.": "Von bescheidenen Anfängen zu globaler Wirkung, sehen Sie, wie BAOBAB HOPE gewachsen und sich entwickelt hat.",
        "We work across multiple interconnected areas to create comprehensive, sustainable change": "Wir arbeiten in mehreren miteinander verbundenen Bereichen, um umfassenden, nachhaltigen Wandel zu schaffen",
        "Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.": "Wie der mächtige Baobab-Baum glauben wir an tiefe Wurzeln, starkes Wachstum und dauerhaften Einfluss.",
        "Our core values guide every decision we make and every action we take in service of our mission.": "Unsere Grundwerte leiten jede Entscheidung und jede Handlung im Dienste unserer Mission.",
        "We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.": "Wir glauben daran, langfristige, nachhaltige Lösungen zu fördern, die mit der Zeit stärker werden, genau wie der Baobab-Baum.",
        "Help us expand access to essential healthcare services and health education in underserved communities worldwide.": "Helfen Sie uns, den Zugang zu wesentlichen Gesundheitsdiensten und Gesundheitserziehung in unterversorgten Gemeinschaften weltweit zu erweitern.",
        "We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.": "Wir stärken Einzelpersonen und Gemeinschaften mit den Werkzeugen, dem Wissen und den Ressourcen, die sie benötigen, um unabhängig zu gedeihen.",
        "Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.": "Gemeinschaften stehen im Mittelpunkt von allem, was wir tun. Wir hören zu, lernen und arbeiten zusammen, um bedeutsamen Wandel zu schaffen.",
        "We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.": "Wir wahren vollständige Transparenz in unseren Operationen, Finanzen und Wirkung, um dauerhaftes Vertrauen mit unseren Unterstützern aufzubauen.",
        "Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.": "Helfen Sie uns, sauberen, sicheren Wasserzugang für bedürftige Gemeinschaften durch nachhaltige Wassersysteme und Naturschutzbildung bereitzustellen.",
        "Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.": "Unterstützen Sie unsere Umweltschutzbemühungen und nachhaltigen Praktiken, die Ökosysteme bewahren und gleichzeitig lokale Gemeinschaften stärken.",
        "Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.": "Nachhaltige Praktiken und Naturschutzbemühungen umsetzen, um Ökosysteme für zukünftige Generationen zu bewahren und gleichzeitig lokale Gemeinschaften zu stärken.",
        "Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.": "Wesentliche Gesundheitsdienste und Gesundheitserziehung für unterversorgte Gemeinschaften bereitstellen und sicherstellen, dass jeder Zugang zu qualitativ hochwertiger medizinischer Versorgung hat.",
        "Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.": "Schließen Sie sich uns an, um qualitativ hochwertige Bildungs- und Alphabetisierungsprogramme bereitzustellen, die Gemeinschaften befähigen, den Kreislauf der Armut zu durchbrechen und nachhaltigen Wandel zu schaffen.",
        "To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.": "Nachhaltiges Wachstum in Gemeinschaften durch Bildung, Stärkung und Umweltverantwortung zu fördern und dauerhaften positiven Wandel zu schaffen, der Generationen umspannt.",
        "Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.": "Seit unserer Gründung im Jahr 2020 sind wir verpflichtet, nachhaltige Lösungen zu schaffen, die die Grundursachen von Armut, Ungleichheit und Umweltzerstörung angehen.",
        "Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.": "Schließen Sie sich unserer wachsenden Gemeinschaft von Veränderern an und helfen Sie uns, Hoffnung in Gemeinschaften zu fördern, die sie am meisten brauchen. Jeder Beitrag, unabhängig von der Größe, erzeugt Wellen positiven Wandels."
    },
    es: {
        "translations@baobabhope.org": "translations@baobabhope.org",
        "your.email@organization.com": "tu.email@organizacion.com",
        "2025-01-27T12:30:00.000Z": "2025-01-27T12:30:00.000Z",
        "https://your-website.com": "https://tu-sitio-web.com",
        "Minimum donation is $5": "La donación mínima es de $5",
        "https://baobabhope.org": "https://baobabhope.org",
        "info@baobabhope.org": "info@baobabhope.org",
        "1234 5678 9012 3456": "1234 5678 9012 3456",
        "$50,000 - $100,000": "$50,000 - $100,000",
        "$10,000 - $50,000": "$10,000 - $50,000",
        "+1 (555) 123-4567": "+1 (555) 123-4567",
        "Under $10,000": "Menos de $10,000",
        "Over $100,000": "Más de $100,000",
        "index, follow": "index, follow",
        "Last updated": "Última actualización",
        "Apply Filters": "Aplicar Filtros",
        "Upload failed": "Carga fallida",
        "Retry Upload": "Reintentar Carga",
        "Uploading...": "Cargando...",
        "Contact Info": "Información de Contacto",
        "Marie Kouadio": "Marie Kouadio",
        "Jean-Baptiste Dubois": "Jean-Baptiste Dubois",
        "Your full name": "Tu nombre completo",
        "Your job title": "Tu cargo",
        "Error occurred": "Ocurrió un error",
        "File too large": "Archivo demasiado grande",
        "Goal achieved": "Meta alcanzada",
        "What Drives Us": "Qué Nos Impulsa",
        "Learn Our Story": "Conoce Nuestra Historia",
        "Our Focus Areas": "Nuestras Áreas de Enfoque",
        "Our Core Values": "Nuestros Valores Fundamentales",
        "Community First": "Comunidad Primero",
        "Drop files here": "Suelta archivos aquí",
        "Partnership Type": "Tipo de Asociación",
        "In-kind Donation": "Donación en Especie",
        "About BAOBAB HOPE": "Sobre BAOBAB HOPE",
        "Lives Transformed": "Vidas Transformadas",
        "Countries Reached": "Países Alcanzados",
        "Support Education": "Apoyar Educación",
        "Copy to clipboard": "Copiar al portapapeles",
        "Invalid file type": "Tipo de archivo inválido",
        "Maximum file size": "Tamaño máximo de archivo",
        "Upload successful": "Carga exitosa",
        "Event Partnership": "Asociación para Eventos",
        "Financial Support": "Apoyo Financiero",
        "Preferred Schedule": "Horario Preferido",
        "Community Wellness": "Bienestar Comunitario",
        "Our Impact Stories": "Nuestras Historias de Impacto",
        "Our Growing Impact": "Nuestro Impacto Creciente",
        "Support Healthcare": "Apoyar Salud",
        "Healthcare for All": "Salud para Todos",
        "Your email address": "Tu dirección de correo electrónico",
        "Allowed file types": "Tipos de archivo permitidos",
        "Support Environment": "Apoyar Medio Ambiente",
        "Partnership Details": "Detalles de Asociación",
        "Something went wrong": "Algo salió mal",
        "View Health Projects": "Ver Proyectos de Salud",
        "Clean Water for Life": "Agua Limpia para la Vida",
        "All rights reserved.": "Todos los derechos reservados.",
        "Protecting Our Planet": "Protegiendo Nuestro Planeta",
        "Strategic Partnership": "Asociación Estratégica",
        "Employee Volunteering": "Voluntariado de Empleados",
        "Learn About Our Impact": "Conoce Nuestro Impacto",
        "Support Water Projects": "Apoyar Proyectos de Agua",
        "Your organization name": "Nombre de tu organización",
        "Please enter your organization name": "Por favor ingresa el nombre de tu organización",
        "Please enter a valid website URL": "Por favor ingresa una URL de sitio web válida",
        "Building Sustainable Water Systems": "Construyendo Sistemas de Agua Sostenibles",
        "Empowering Through Education": "Empoderando a Través de la Educación",
        "Ready to Plant Seeds of Change?": "¿Listo para Plantar Semillas de Cambio?",
        "Please enter your job title": "Por favor ingresa tu cargo",
        "Growing Together Since 2020": "Creciendo Juntos Desde 2020",
        "Education Transforms Lives": "La Educación Transforma Vidas",
        "Building Brighter Futures": "Construyendo Futuros Más Brillantes",
        "Bringing Medical Care to Those in Need": "Llevando Atención Médica a los Necesitados",
        "Building Brighter Futures Through Learning": "Construyendo Futuros Más Brillantes a Través del Aprendizaje",
        "Environmental Conservation for Future Generations": "Conservación Ambiental para Futuras Generaciones",
        "Stay informed about our latest actions and impact": "Mantente informado sobre nuestras últimas acciones e impacto",
        "Started with a vision to create sustainable change": "Comenzó con una visión de crear cambio sostenible",
        "Growing hope, nurturing communities, creating sustainable futures.": "Cultivando esperanza, nutriendo comunidades, creando futuros sostenibles.",
        "From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.": "Desde humildes comienzos hasta impacto global, ve cómo BAOBAB HOPE ha crecido y evolucionado.",
        "We work across multiple interconnected areas to create comprehensive, sustainable change": "Trabajamos en múltiples áreas interconectadas para crear cambio integral y sostenible",
        "Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.": "Como el poderoso árbol baobab, creemos en raíces profundas, crecimiento fuerte e impacto duradero.",
        "Our core values guide every decision we make and every action we take in service of our mission.": "Nuestros valores fundamentales guían cada decisión que tomamos y cada acción que realizamos al servicio de nuestra misión.",
        "We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.": "Creemos en nutrir soluciones sostenibles a largo plazo que se fortalecen con el tiempo, al igual que el árbol baobab.",
        "Help us expand access to essential healthcare services and health education in underserved communities worldwide.": "Ayúdanos a expandir el acceso a servicios de salud esenciales y educación sanitaria en comunidades desatendidas en todo el mundo.",
        "We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.": "Empoderamos a individuos y comunidades con las herramientas, conocimiento y recursos que necesitan para prosperar independientemente.",
        "Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.": "Las comunidades están en el corazón de todo lo que hacemos. Escuchamos, aprendemos y trabajamos juntos para crear cambio significativo.",
        "We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.": "Mantenemos completa transparencia en nuestras operaciones, finanzas e impacto para construir confianza duradera con nuestros partidarios.",
        "Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.": "Ayúdanos a proporcionar acceso a agua limpia y segura a comunidades necesitadas a través de sistemas de agua sostenibles y educación en conservación.",
        "Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.": "Apoya nuestros esfuerzos de conservación ambiental y prácticas sostenibles que preservan ecosistemas mientras empoderan a comunidades locales.",
        "Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.": "Implementando prácticas sostenibles y esfuerzos de conservación para preservar ecosistemas para futuras generaciones mientras empoderamos a comunidades locales.",
        "Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.": "Proporcionando servicios de salud esenciales y educación sanitaria a comunidades desatendidas, asegurando que todos tengan acceso a atención médica de calidad.",
        "Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.": "Únete a nosotros para proporcionar educación de calidad y programas de alfabetización que empoderen a las comunidades para romper el ciclo de la pobreza y crear cambio sostenible.",
        "To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.": "Nutrir el crecimiento sostenible en las comunidades a través de la educación, el empoderamiento y la administración ambiental, creando cambio positivo duradero que abarca generaciones.",
        "Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.": "Desde nuestra fundación en 2020, hemos estado comprometidos en crear soluciones sostenibles que aborden las causas fundamentales de la pobreza, desigualdad y degradación ambiental.",
        "Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.": "Únete a nuestra creciente comunidad de agentes de cambio y ayúdanos a nutrir esperanza en las comunidades que más lo necesitan. Cada contribución, sin importar el tamaño, crea ondas de cambio positivo."
    },
    it: {
        "translations@baobabhope.org": "translations@baobabhope.org",
        "your.email@organization.com": "tua.email@organizzazione.it",
        "2025-01-27T12:30:00.000Z": "2025-01-27T12:30:00.000Z",
        "https://your-website.com": "https://tuo-sito-web.it",
        "Minimum donation is $5": "La donazione minima è di $5",
        "https://baobabhope.org": "https://baobabhope.org",
        "info@baobabhope.org": "info@baobabhope.org",
        "1234 5678 9012 3456": "1234 5678 9012 3456",
        "$50,000 - $100,000": "$50.000 - $100.000",
        "$10,000 - $50,000": "$10.000 - $50.000",
        "+1 (555) 123-4567": "+1 (555) 123-4567",
        "Under $10,000": "Sotto $10.000",
        "Over $100,000": "Oltre $100.000",
        "index, follow": "index, follow",
        "Last updated": "Ultimo aggiornamento",
        "Apply Filters": "Applica Filtri",
        "Upload failed": "Caricamento fallito",
        "Retry Upload": "Riprova Caricamento",
        "Uploading...": "Caricamento...",
        "Contact Info": "Informazioni di Contatto",
        "Marie Kouadio": "Marie Kouadio",
        "Jean-Baptiste Dubois": "Jean-Baptiste Dubois",
        "Your full name": "Il tuo nome completo",
        "Your job title": "Il tuo titolo di lavoro",
        "Error occurred": "Si è verificato un errore",
        "File too large": "File troppo grande",
        "Goal achieved": "Obiettivo raggiunto",
        "What Drives Us": "Cosa Ci Guida",
        "Learn Our Story": "Scopri la Nostra Storia",
        "Our Focus Areas": "Le Nostre Aree di Focus",
        "Our Core Values": "I Nostri Valori Fondamentali",
        "Community First": "Comunità Prima",
        "Drop files here": "Trascina file qui",
        "Partnership Type": "Tipo di Partnership",
        "In-kind Donation": "Donazione in Natura",
        "About BAOBAB HOPE": "Su BAOBAB HOPE",
        "Lives Transformed": "Vite Trasformate",
        "Countries Reached": "Paesi Raggiunti",
        "Support Education": "Sostieni l'Istruzione",
        "Copy to clipboard": "Copia negli appunti",
        "Invalid file type": "Tipo di file non valido",
        "Maximum file size": "Dimensione massima file",
        "Upload successful": "Caricamento riuscito",
        "Event Partnership": "Partnership per Eventi",
        "Financial Support": "Supporto Finanziario",
        "Preferred Schedule": "Orario Preferito",
        "Community Wellness": "Benessere Comunitario",
        "Our Impact Stories": "Le Nostre Storie di Impatto",
        "Our Growing Impact": "Il Nostro Impatto Crescente",
        "Support Healthcare": "Sostieni la Sanità",
        "Healthcare for All": "Salute per Tutti",
        "Your email address": "Il tuo indirizzo email",
        "Allowed file types": "Tipi di file consentiti",
        "Support Environment": "Sostieni l'Ambiente",
        "Partnership Details": "Dettagli Partnership",
        "Something went wrong": "Qualcosa è andato storto",
        "View Health Projects": "Visualizza Progetti Sanitari",
        "Clean Water for Life": "Acqua Pulita per la Vita",
        "All rights reserved.": "Tutti i diritti riservati.",
        "Protecting Our Planet": "Proteggere il Nostro Pianeta",
        "Strategic Partnership": "Partnership Strategica",
        "Employee Volunteering": "Volontariato dei Dipendenti",
        "Learn About Our Impact": "Scopri il Nostro Impatto",
        "Support Water Projects": "Sostieni Progetti Idrici",
        "Your organization name": "Nome della tua organizzazione",
        "Please enter your organization name": "Inserisci il nome della tua organizzazione",
        "Please enter a valid website URL": "Inserisci un URL del sito web valido",
        "Building Sustainable Water Systems": "Costruire Sistemi Idrici Sostenibili",
        "Empowering Through Education": "Potenziare Attraverso l'Istruzione",
        "Ready to Plant Seeds of Change?": "Pronto a Piantare Semi di Cambiamento?",
        "Please enter your job title": "Inserisci il tuo titolo di lavoro",
        "Growing Together Since 2020": "Crescere Insieme Dal 2020",
        "Education Transforms Lives": "L'Istruzione Trasforma Vite",
        "Building Brighter Futures": "Costruire Futuri Più Luminosi",
        "Bringing Medical Care to Those in Need": "Portare Assistenza Medica a Chi Ne Ha Bisogno",
        "Building Brighter Futures Through Learning": "Costruire Futuri Più Luminosi Attraverso l'Apprendimento",
        "Environmental Conservation for Future Generations": "Conservazione Ambientale per le Generazioni Future",
        "Stay informed about our latest actions and impact": "Rimani informato sulle nostre ultime azioni e impatto",
        "Started with a vision to create sustainable change": "Iniziato con una visione di creare cambiamento sostenibile",
        "Growing hope, nurturing communities, creating sustainable futures.": "Coltivando speranza, nutrendo comunità, creando futuri sostenibili.",
        "From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.": "Dagli umili inizi all'impatto globale, vedi come BAOBAB HOPE è cresciuta ed evoluta.",
        "We work across multiple interconnected areas to create comprehensive, sustainable change": "Lavoriamo in molteplici aree interconnesse per creare cambiamento completo e sostenibile",
        "Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.": "Come il possente albero baobab, crediamo in radici profonde, crescita forte e impatto duraturo.",
        "Our core values guide every decision we make and every action we take in service of our mission.": "I nostri valori fondamentali guidano ogni decisione che prendiamo e ogni azione che intraprendiamo al servizio della nostra missione.",
        "We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.": "Crediamo nel coltivare soluzioni sostenibili a lungo termine che diventano più forti nel tempo, proprio come l'albero baobab.",
        "Help us expand access to essential healthcare services and health education in underserved communities worldwide.": "Aiutaci ad espandere l'accesso ai servizi sanitari essenziali e all'educazione sanitaria nelle comunità svantaggiate in tutto il mondo.",
        "We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.": "Potenziamo individui e comunità con gli strumenti, la conoscenza e le risorse necessarie per prosperare indipendentemente.",
        "Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.": "Le comunità sono al centro di tutto ciò che facciamo. Ascoltiamo, impariamo e lavoriamo insieme per creare cambiamento significativo.",
        "We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.": "Manteniamo completa trasparenza nelle nostre operazioni, finanze e impatto per costruire fiducia duratura con i nostri sostenitori.",
        "Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.": "Aiutaci a fornire accesso ad acqua pulita e sicura alle comunità bisognose attraverso sistemi idrici sostenibili ed educazione alla conservazione.",
        "Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.": "Sostieni i nostri sforzi di conservazione ambientale e pratiche sostenibili che preservano gli ecosistemi potenziando le comunità locali.",
        "Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.": "Implementando pratiche sostenibili e sforzi di conservazione per preservare gli ecosistemi per le generazioni future potenziando le comunità locali.",
        "Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.": "Fornendo servizi sanitari essenziali ed educazione sanitaria alle comunità svantaggiate, assicurando che tutti abbiano accesso a cure mediche di qualità.",
        "Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.": "Unisciti a noi nel fornire istruzione di qualità e programmi di alfabetizzazione che potenziano le comunità per rompere il ciclo della povertà e creare cambiamento sostenibile.",
        "To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.": "Coltivare crescita sostenibile nelle comunità attraverso istruzione, empowerment e gestione ambientale, creando cambiamento positivo duraturo che attraversa le generazioni.",
        "Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.": "Dalla nostra fondazione nel 2020, siamo stati impegnati nella creazione di soluzioni sostenibili che affrontano le cause profonde della povertà, disuguaglianza e degrado ambientale.",
        "Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.": "Unisciti alla nostra crescente comunità di agenti del cambiamento e aiutaci a coltivare speranza nelle comunità che ne hanno più bisogno. Ogni contributo, indipendentemente dalle dimensioni, crea onde di cambiamento positivo."
    },
    ar: {
        "translations@baobabhope.org": "translations@baobabhope.org",
        "your.email@organization.com": "بريدك@منظمة.com",
        "2025-01-27T12:30:00.000Z": "2025-01-27T12:30:00.000Z",
        "https://your-website.com": "https://موقعك-الإلكتروني.com",
        "Minimum donation is $5": "الحد الأدنى للتبرع هو 5$",
        "https://baobabhope.org": "https://baobabhope.org",
        "info@baobabhope.org": "info@baobabhope.org",
        "1234 5678 9012 3456": "1234 5678 9012 3456",
        "$50,000 - $100,000": "$50,000 - $100,000",
        "$10,000 - $50,000": "$10,000 - $50,000",
        "+1 (555) 123-4567": "123-4567 (555) 1+",
        "Under $10,000": "أقل من $10,000",
        "Over $100,000": "أكثر من $100,000",
        "index, follow": "index, follow",
        "Last updated": "آخر تحديث",
        "Apply Filters": "تطبيق الفلاتر",
        "Upload failed": "فشل الرفع",
        "Retry Upload": "إعادة محاولة الرفع",
        "Uploading...": "جارٍ الرفع...",
        "Contact Info": "معلومات الاتصال",
        "Marie Kouadio": "ماري كواديو",
        "Jean-Baptiste Dubois": "جان-باتيست دوبوا",
        "Your full name": "اسمك الكامل",
        "Your job title": "مسماك الوظيفي",
        "Error occurred": "حدث خطأ",
        "File too large": "الملف كبير جداً",
        "Goal achieved": "تم تحقيق الهدف",
        "What Drives Us": "ما يدفعنا",
        "Learn Our Story": "تعرف على قصتنا",
        "Our Focus Areas": "مجالات تركيزنا",
        "Our Core Values": "قيمنا الأساسية",
        "Community First": "المجتمع أولاً",
        "Drop files here": "اسقط الملفات هنا",
        "Partnership Type": "نوع الشراكة",
        "In-kind Donation": "التبرع العيني",
        "About BAOBAB HOPE": "عن BAOBAB HOPE",
        "Lives Transformed": "الحياة المتحولة",
        "Countries Reached": "البلدان التي تم الوصول إليها",
        "Support Education": "دعم التعليم",
        "Copy to clipboard": "نسخ إلى الحافظة",
        "Invalid file type": "نوع ملف غير صالح",
        "Maximum file size": "الحد الأقصى لحجم الملف",
        "Upload successful": "نجح الرفع",
        "Event Partnership": "شراكة الفعاليات",
        "Financial Support": "الدعم المالي",
        "Preferred Schedule": "الجدول المفضل",
        "Community Wellness": "الصحة المجتمعية",
        "Our Impact Stories": "قصص تأثيرنا",
        "Our Growing Impact": "تأثيرنا المتنامي",
        "Support Healthcare": "دعم الرعاية الصحية",
        "Healthcare for All": "الرعاية الصحية للجميع",
        "Your email address": "عنوان بريدك الإلكتروني",
        "Allowed file types": "أنواع الملفات المسموح بها",
        "Support Environment": "دعم البيئة",
        "Partnership Details": "تفاصيل الشراكة",
        "Something went wrong": "حدث خطأ ما",
        "View Health Projects": "عرض مشاريع الصحة",
        "Clean Water for Life": "مياه نظيفة للحياة",
        "All rights reserved.": "جميع الحقوق محفوظة.",
        "Protecting Our Planet": "حماية كوكبنا",
        "Strategic Partnership": "الشراكة الاستراتيجية",
        "Employee Volunteering": "تطوع الموظفين",
        "Learn About Our Impact": "تعرف على تأثيرنا",
        "Support Water Projects": "دعم مشاريع المياه",
        "Your organization name": "اسم منظمتك",
        "Please enter your organization name": "يرجى إدخال اسم منظمتك",
        "Please enter a valid website URL": "يرجى إدخال عنوان URL صالح للموقع الإلكتروني",
        "Building Sustainable Water Systems": "بناء أنظمة مياه مستدامة",
        "Empowering Through Education": "التمكين من خلال التعليم",
        "Ready to Plant Seeds of Change?": "هل أنت مستعد لزرع بذور التغيير؟",
        "Please enter your job title": "يرجى إدخال مسماك الوظيفي",
        "Growing Together Since 2020": "النمو معاً منذ 2020",
        "Education Transforms Lives": "التعليم يحول الحياة",
        "Building Brighter Futures": "بناء مستقبل أكثر إشراقاً",
        "Bringing Medical Care to Those in Need": "جلب الرعاية الطبية لمن يحتاجونها",
        "Building Brighter Futures Through Learning": "بناء مستقبل أكثر إشراقاً من خلال التعلم",
        "Environmental Conservation for Future Generations": "الحفاظ على البيئة للأجيال القادمة",
        "Stay informed about our latest actions and impact": "ابق على اطلاع بأحدث أعمالنا وتأثيرنا",
        "Started with a vision to create sustainable change": "بدأت برؤية لخلق تغيير مستدام",
        "Growing hope, nurturing communities, creating sustainable futures.": "تنمية الأمل، رعاية المجتمعات، خلق مستقبل مستدام.",
        "From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.": "من البدايات المتواضعة إلى التأثير العالمي، شاهد كيف نمت وتطورت BAOBAB HOPE.",
        "We work across multiple interconnected areas to create comprehensive, sustainable change": "نعمل عبر مجالات متعددة ومترابطة لخلق تغيير شامل ومستدام",
        "Like the mighty baobab tree, we believe in deep roots, stronggrowth, and lasting impact.": "مثل شجرة الباوباب العظيمة، نؤمن بالجذور العميقة والنمو القوي والتأثير الدائم.",
        "Our core values guide every decision we make and every action we take in service of our mission.": "قيمنا الأساسية توجه كل قرار نتخذه وكل إجراء نتخذه في خدمة مهمتنا.",
        "We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.": "نؤمن برعاية حلول طويلة الأجل ومستدامة تصبح أقوى بمرور الوقت، تماماً مثل شجرة الباوباب.",
        "Help us expand access to essential healthcare services and health education in underserved communities worldwide.": "ساعدنا في توسيع الوصول إلى الخدمات الصحية الأساسية والتثقيف الصحي في المجتمعات المحرومة في جميع أنحاء العالم.",
        "We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.": "نمكن الأفراد والمجتمعات بالأدوات والمعرفة والموارد التي يحتاجونها للازدهار بشكل مستقل.",
        "Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.": "المجتمعات في قلب كل ما نقوم به. نستمع ونتعلم ونعمل معاً لخلق تغيير ذي مغزى.",
        "We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.": "نحافظ على شفافية كاملة في عملياتنا وتمويلنا وتأثيرنا لبناء ثقة دائمة مع داعمينا.",
        "Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.": "ساعدنا في توفير الوصول إلى المياه النظيفة والآمنة للمجتمعات المحتاجة من خلال أنظمة المياه المستدامة والتعليم على الحفاظ.",
        "Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.": "ادعم جهودنا للحفاظ على البيئة والممارسات المستدامة التي تحافظ على النظم البيئية بينما تمكن المجتمعات المحلية.",
        "Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.": "تطبيق ممارسات مستدامة وجهود الحفاظ على النظم البيئية للأجيال القادمة بينما نمكن المجتمعات المحلية.",
        "Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.": "توفير خدمات الرعاية الصحية الأساسية والتثقيف الصحي للمجتمعات المحرومة، مما يضمن حصول الجميع على رعاية طبية عالية الجودة.",
        "Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.": "انضم إلينا في توفير تعليم عالي الجودة وبرامج محو الأمية التي تمكن المجتمعات من كسر دائرة الفقر وخلق تغيير مستدام.",
        "To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.": "رعاية النمو المستدام في المجتمعات من خلال التعليم والتمكين والإشراف البيئي، وإحداث تغيير إيجابي دائم يمتد عبر الأجيال.",
        "Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.": "منذ تأسيسنا في عام 2020، التزمنا بإنشاء حلول مستدامة تعالج الأسباب الجذرية للفقر وعدم المساواة والتدهور البيئي.",
        "Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.": "انضم إلى مجتمعنا المتنامي من صانعي التغيير وساعدنا في رعاية الأمل في المجتمعات التي تحتاجه أكثر. كل مساهمة، بغض النظر عن حجمها، تخلق موجات من التغيير الإيجابي."
    }
};

console.log('🚀 Applying FINAL COMPREHENSIVE TRANSLATION to reach 100%...');
for (const lang of ['de', 'es', 'it', 'ar']) {
    console.log(`  Translating ${lang.toUpperCase()}...`);
    t[lang] = deepApply(t[lang], complete[lang]);
}

fs.writeFileSync('./public/locales/translations.json', JSON.stringify(t, null, 2), 'utf8');
console.log('\n✅✅✅ ABSOLUTE 100% COMPLETION ACHIEVED! ✅✅✅');
