const fs = require('fs');
const translations = JSON.parse(fs.readFileSync('./public/locales/translations.json', 'utf8'));

function apply(obj, dict) {
    if (!obj || typeof obj !== 'object' || Array.isArray(obj)) {
        return typeof obj === 'string' && dict[obj] ? dict[obj] : obj;
    }
    const result = {};
    for (const key in obj) {
        result[key] = apply(obj[key], dict);
    }
    return result;
}

// SPANISH - Complete final translations
const spanishFinal = {
    '  'Your organization name': 'Nombre de tu organización',
  'Please enter your organization name': 'Por favor ingresa el nombre de tu organización',
    'Website': 'Sitio web',
    'https://your-website.com': 'https://tu-sitio-web.com',
    'Please enter a valid website URL': 'Por favor ingresa una URL de sitio web válida',
    'Your full name': 'Tu nombre completo',
    'Please enter the contact person\\'s name': 'Por favor ingresa el nombre de la persona de contacto',
  'Job Title': 'Cargo',
    'Your job title': 'Tu cargo',
    'Please enter your job title': 'Por favor ingresa tu cargo',
    'your.email@organization.com': 'tu.email@organizacion.com',
    'Partnership Details': 'Detalles de Asociación',
    'Partnership Type': 'Tipo de Asociación',
    'Financial Support': 'Apoyo Financiero',
    'In-kind Donation': 'Donación en Especie',
    'Employee Volunteering': 'Voluntariado de Empleados',
    'Strategic Partnership': 'Asociación Estratégica',
    'Event Partnership': 'Asociación para Eventos',
    'Preferences': 'Preferencias',
    'Error occurred': 'Ocurrió un error',
    'ago': 'hace',
    'now': 'ahora',
    'second': 'segundo',
    'seconds': 'segundos',
    'First': 'Primero',
    'Last': 'Último',
    'Showing': 'Mostrando',
    'per page': 'por página',
    'Apply Filters': 'Aplicar Filtros',
    'Ascending': 'Ascendente',
    'Descending': 'Descendente',
    'Select File': 'Seleccionar Archivo',
    'Drop files here': 'Suelta archivos aquí',
    'Upload successful': 'Carga exitosa',
    'Upload failed': 'Carga fallida',
    'Retry Upload': 'Reintentar Carga',
    'Remove File': 'Eliminar Archivo',
    'Maximum file size': 'Tamaño máximo de archivo',
    'Allowed file types': 'Tipos de archivo permitidos',
    'File too large': 'Archivo demasiado grande',
    'Invalid file type': 'Tipo de archivo inválido',
    'Copy to clipboard': 'Copiar al portapapeles',
    'Growing hope, nurturing communities, creating sustainable futures.': 'Cultivando esperanza, nutriendo comunidades, creando futuros sostenibles.',
    'Contact Info': 'Información de Contacto',
    'Stay informed about our latest actions and impact': 'Mantente informado sobre nuestras últimas acciones e impacto',
    'All rights reserved.': 'Todos los derechos reservados.',
    'Empowering Through Education': 'Empoderando a Través de la Educación',
    'Building Brighter Futures': 'Construyendo Futuros Más Brillantes',
    'Education Transforms Lives': 'La Educación Transforma Vidas',
    'Building Brighter Futures Through Learning': 'Construyendo Futuros Más Brillantes a Través del Aprendizaje',
    'Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.': 'Únete a nosotros para proporcionar educación de calidad y programas de alfabetización que empoderen a las comunidades para romper el ciclo de la pobreza y crear cambio sostenible.',
    'Support Education': 'Apoyar Educación',
    'Bringing Medical Care to Those in Need': 'Llevando Atención Médica a los Necesitados',
    'Help us expand access to essential healthcare services and health education in underserved communities worldwide.': 'Ayúdanos a expandir el acceso a servicios de salud esenciales y educación sanitaria en comunidades desatendidas en todo el mundo.',
    'Support Healthcare': 'Apoyar Salud',
    'Environmental Conservation for Future Generations': 'Conservación Ambiental para Futuras Generaciones',
    'Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.': 'Apoya nuestros esfuerzos de conservación ambiental y prácticas sostenibles que preservan ecosistemas mientras empoderan a comunidades locales.',
    'Support Environment': 'Apoyar Medio Ambiente',
    'Clean Water for Life': 'Agua Limpia para la Vida',
    'Building Sustainable Water Systems': 'Construyendo Sistemas de Agua Sostenibles',
    'Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.': 'Ayúdanos a proporcionar acceso a agua limpia y segura a comunidades necesitadas a través de sistemas de agua sostenibles y educación en conservación.',
    'Support Water Projects': 'Apoyar Proyectos de Agua',
    'Discover how we\\'re creating sustainable change in communities worldwide': 'Descubre cómo estamos creando cambio sostenible en comunidades de todo el mundo',
  'Ready to Plant Seeds of Change?': '¿Listo para Plantar Semillas de Cambio?',
    'Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.': 'Únete a nuestra creciente comunidad de agentes de cambio y ayúdanos a nutrir esperanza en las comunidades que más lo necesitan. Cada contribución, sin importar el tamaño, crea ondas de cambio positivo.',
    'Learn Our Story': 'Conoce Nuestra Historia',
    'We work across multiple interconnected areas to create comprehensive, sustainable change': 'Trabajamos en múltiples áreas interconectadas para crear cambio integral y sostenible',
    'Implementing sustainable practices and conservation of efforts to preserve ecosystems for future generations while empowering local communities.': 'Implementando prácticas sostenibles y esfuerzos de conservación para preservar ecosistemas para futuras generaciones mientras empoderamos a comunidades locales.',
    'Learn About Our Impact': 'Conoce Nuestro Impacto',
    'Community Wellness': 'Bienestar Comunitario',
    'Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.': 'Proporcionando servicios de salud esenciales y educación sanitaria a comunidades desatendidas, asegurando que todos tengan acceso a atención médica de calidad.',
    'Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.': 'Como el poderoso árbol baobab, creemos en raíces profundas, crecimiento fuerte e impacto duradero.',
    'Our Purpose': 'Nuestro Propósito',
    'To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.': 'Nutrir el crecimiento sostenible en las comunidades a través de la educación, el empoderamiento y la administración ambiental, creando cambio positivo duradero que abarca generaciones.',
    'Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.': 'Desde nuestra fundación en 2020, hemos estado comprometidos en crear soluciones sostenibles que aborden las causas fundamentales de la pobreza, desigualdad y degradación ambiental.',
    'What Drives Us': 'Qué Nos Impulsa',
    'Our core values guide every decision we make and every action we take in service of our mission.': 'Nuestros valores fundamentales guían cada decisión que tomamos y cada acción que realizamos al servicio de nuestra misión.',
    'We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.': 'Creemos en nutrir soluciones sostenibles a largo plazo que se fortalecen con el tiempo, al igual que el árbol baobab.',
    'Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.': 'Las comunidades están en el corazón de todo lo que hacemos. Escuchamos, aprendemos y trabajamos juntos para crear cambio significativo.',
    'We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.': 'Mantenemos completa transparencia en nuestras operaciones, finanzas e impacto para construir confianza duradera con nuestros partidarios.',
    'We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.': 'Empoderamos a individuos y comunidades con las herramientas, conocimiento y recursos que necesitan para prosperar independientemente.',
    'Our Journey': 'Nuestro Viaje',
    'Growing Together Since 2020': 'Creciendo Juntos Desde 2020',
    'From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.': 'Desde humildes comienzos hasta impacto global, ve cómo BAOBAB HOPE ha crecido y evolucionado.',
    'Started with a vision to create sustainable change': 'Comenzó con una visión de crear cambio sostenible',
    '$25': '$25',
    '$50': '$50',
    'USD': 'USD',
    '${amount}': '${amount}',
    'gal': 'gal'
};

// ITALIAN - Complete final translations  
const italianFinal = {
    'Your organization name': 'Nome della tua organizzazione',
    'Please enter your organization name': 'Inserisci il nome della tua organizzazione',
    'Website': 'Sito web',
    'https://your-website.com': 'https://tuo-sito-web.it',
    'Please enter a valid website URL': 'Inserisci un URL del sito web valido',
    'Your full name': 'Il tuo nome completo',
    'Please enter the contact person\\'s name': 'Inserisci il nome della persona di contatto',
  'Job Title': 'Titolo di Lavoro',
    'Your job title': 'Il tuo titolo di lavoro',
    'Please enter your job title': 'Inserisci il tuo titolo di lavoro',
    'your.email@organization.com': 'tua.email@organizzazione.it',
    'Partnership Details': 'Dettagli Partnership',
    'Partnership Type': 'Tipo di Partnership',
    'Financial Support': 'Supporto Finanziario',
    'In-kind Donation': 'Donazione in Natura',
    'Employee Volunteering': 'Volontariato dei Dipendenti',
    'Strategic Partnership': 'Partnership Strategica',
    'Event Partnership': 'Partnership per Eventi',
    'Preferred Schedule': 'Orario Preferito',
    'Preferences': 'Preferenze',
    'Error occurred': 'Si è verificato un errore',
    'ago': 'fa',
    'now': 'ora',
    'second': 'secondo',
    'seconds': 'secondi',
    'First': 'Primo',
    'Last': 'Ultimo',
    'Showing': 'Mostrando',
    'per page': 'per pagina',
    'Apply Filters': 'Applica Filtri',
    'Ascending': 'Ascendente',
    'Descending': 'Discendente',
    'Select File': 'Seleziona File',
    'Drop files here': 'Trascina file qui',
    'Upload successful': 'Caricamento riuscito',
    'Upload failed': 'Caricamento fallito',
    'Retry Upload': 'Riprova Caricamento',
    'Remove File': 'Rimuovi File',
    'Maximum file size': 'Dimensione massima file',
    'Allowed file types': 'Tipi di file consentiti',
    'File too large': 'File troppo grande',
    'Invalid file type': 'Tipo di file non valido',
    'Copy to clipboard': 'Copia negli appunti',
    'Growing hope, nurturing communities, creating sustainable futures.': 'Coltivando speranza, nutrendo comunità, creando futuri sostenibili.',
    'Contact Info': 'Informazioni di Contatto',
    'Stay informed about our latest actions and impact': 'Rimani informato sulle nostre ultime azioni e impatto',
    'All rights reserved.': 'Tutti i diritti riservati.',
    'Empowering Through Education': 'Potenziare Attraverso l\\'Istruzione',
  'Building Brighter Futures': 'Costruire Futuri Più Luminosi',
    'Education Transforms Lives': 'L\\'Istruzione Trasforma Vite',
  'Building Brighter Futures Through Learning': 'Costruire Futuri Più Luminosi Attraverso l\\'Apprendimento',
  'Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.': 'Unisciti a noi nel fornire istruzione di qualità e programmi di alfabetizzazione che potenziano le comunità per rompere il ciclo della povertà e creare cambiamento sostenibile.',
    'Support Education': 'Sostieni l\\'Istruzione',
  'Bringing Medical Care to Those in Need': 'Portare Assistenza Medica a Chi Ne Ha Bisogno',
    'Help us expand access to essential healthcare services and health education in underserved communities worldwide.': 'Aiutaci ad espandere l\\'accesso ai servizi sanitari essenziali e all\\'educazione sanitaria nelle comunità svantaggiate in tutto il mondo.',
    'Support Healthcare': 'Sostieni la Sanità',
    'Environmental Conservation for Future Generations': 'Conservazione Ambientale per le Generazioni Future',
    'Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.': 'Sostieni i nostri sforzi di conservazione ambientale e pratiche sostenibili che preservano gli ecosistemi potenziando le comunità locali.',
    'Support Environment': 'Sostieni l\\'Ambiente',
  'Clean Water for Life': 'Acqua Pulita per la Vita',
    'Building Sustainable Water Systems': 'Costruire Sistemi Idrici Sostenibili',
    'Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.': 'Aiutaci a fornire accesso ad acqua pulita e sicura alle comunità bisognose attraverso sistemi idrici sostenibili ed educazione alla conservazione.',
    'Support Water Projects': 'Sostieni Progetti Idrici',
    'Discover how we\\'re creating sustainable change in communities worldwide': 'Scopri come stiamo creando cambiamento sostenibile nelle comunità di tutto il mondo',
  'Ready to Plant Seeds of Change?': 'Pronto a Piantare Semi di Cambiamento?',
    'Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.': 'Unisciti alla nostra crescente comunità di agenti del cambiamento e aiutaci a coltivare speranza nelle comunità che ne hanno più bisogno. Ogni contributo, indipendentemente dalle dimensioni, crea onde di cambiamento positivo.',
    'Learn Our Story': 'Scopri la Nostra Storia',
    'We work across multiple interconnected areas to create comprehensive, sustainable change': 'Lavoriamo in molteplici aree interconnesse per creare cambiamento completo e sostenibile',
    'Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.': 'Implementando pratiche sostenibili e sforzi di conservazione per preservare gli ecosistemi per le generazioni future potenziando le comunità locali.',
    'Learn About Our Impact': 'Scopri il Nostro Impatto',
    'Community Wellness': 'Benessere Comunitario',
    'Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.': 'Fornendo servizi sanitari essenziali ed educazione sanitaria alle comunità svantaggiate, assicurando che tutti abbiano accesso a cure mediche di qualità.',
    'Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.': 'Come il possente albero baobab, crediamo in radici profonde, crescita forte e impatto duraturo.',
    'Our Purpose': 'Il Nostro Scopo',
    'To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.': 'Coltivare crescita sostenibile nelle comunità attraverso istruzione, empowerment e gestione ambientale, creando cambiamento positivo duraturo che attraversa le generazioni.',
    'Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.': 'Dalla nostra fondazione nel 2020, siamo stati impegnati nella creazione di soluzioni sostenibili che affrontano le cause profonde della povertà, disuguaglianza e degrado ambientale.',
    'What Drives Us': 'Cosa Ci Guida',
    'Our core values guide every decision we make and every action we take in service of our mission.': 'I nostri valori fondamentali guidano ogni decisione che prendiamo e ogni azione che intraprendiamo al servizio della nostra missione.',
    'We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.': 'Crediamo nel coltivare soluzioni sostenibili a lungo termine che diventano più forti nel tempo, proprio come l\\'albero baobab.',
  'Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.': 'Le comunità sono al centro di tutto ciò che facciamo. Ascoltiamo, impariamo e lavoriamo insieme per creare cambiamento significativo.',
    'We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.': 'Manteniamo completa trasparenza nelle nostre operazioni, finanze e impatto per costruire fiducia duratura con i nostri sostenitori.',
    'We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.': 'Potenziamo individui e comunità con gli strumenti, la conoscenza e le risorse necessarie per prosperare indipendentemente.',
    'Our Journey': 'Il Nostro Viaggio',
    'Growing Together Since 2020': 'Crescere Insieme Dal 2020',
    'From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.': 'Dagli umili inizi all\\'impatto globale, vedi come BAOBAB HOPE è cresciuta ed evoluta.',
  'Started with a vision to create sustainable change': 'Iniziato con una visione di creare cambiamento sostenibile',
    '$25': '$25',
    '$50': '$50',
    'USD': 'USD',
    '${amount}': '${amount}',
    'gal': 'gal'
};

// ARABIC - Complete final translations
const arabicFinal = {
    'Your organization name': 'اسم منظمتك',
    'Please enter your organization name': 'يرجى إدخال اسم منظمتك',
    'Website': 'الموقع الإلكتروني',
    'https://your-website.com': 'https://موقعك-الإلكتروني.com',
    'Please enter a valid website URL': 'يرجى إدخال عنوان URL صالح للموقع الإلكتروني',
    'Your full name': 'اسمك الكامل',
    'Please enter the contact person\\'s name': 'يرجى إدخال اسم الشخص المسؤول',
  'Job Title': 'المسمى الوظيفي',
    'Your job title': 'مسماك الوظيفي',
    'Please enter your job title': 'يرجى إدخال مسماك الوظيفي',
    'your.email@organization.com': 'بريدك@منظمة.com',
    'Partnership Details': 'تفاصيل الشراكة',
    'Partnership Type': 'نوع الشراكة',
    'Financial Support': 'الدعم المالي',
    'In-kind Donation': 'التبرع العيني',
    'Employee Volunteering': 'تطوع الموظفين',
    'Strategic Partnership': 'الشراكة الاستراتيجية',
    'Event Partnership': 'شراكة الفعاليات',
    'Preferences': 'التفضيلات',
    'Error occurred': 'حدث خطأ',
    'ago': 'مضت',
    'now': 'الآن',
    'second': 'ثانية',
    'seconds': 'ثوانٍ',
    'First': 'الأول',
    'Last': 'الأخير',
    'Showing': 'عرض',
    'per page': 'لكل صفحة',
    'Apply Filters': 'تطبيق الفلاتر',
    'Ascending': 'تصاعدي',
    'Descending': 'تنازلي',
    'Select File': 'اختر ملف',
    'Drop files here': 'اسقط الملفات هنا',
    'Upload successful': 'نجح الرفع',
    'Upload failed': 'فشل الرفع',
    'Retry Upload': 'إعادة محاولة الرفع',
    'Remove File': 'إزالة الملف',
    'Maximum file size': 'الحد الأقصى لحجم الملف',
    'Allowed file types': 'أنواع الملفات المسموح بها',
    'File too large': 'الملف كبير جداً',
    'Invalid file type': 'نوع ملف غير صالح',
    'Copy to clipboard': 'نسخ إلى الحافظة',
    'Growing hope, nurturing communities, creating sustainable futures.': 'تنمية الأمل، رعاية المجتمعات، خلق مستقبل مستدام.',
    'Contact Info': 'معلومات الاتصال',
    'Stay informed about our latest actions and impact': 'ابق على اطلاع بأحدث أعمالنا وتأثيرنا',
    'All rights reserved.': 'جميع الحقوق محفوظة.',
    'Empowering Through Education': 'التمكين من خلال التعليم',
    'Building Brighter Futures': 'بناء مستقبل أكثر إشراقاً',
    'Education Transforms Lives': 'التعليم يحول الحياة',
    'Building Brighter Futures Through Learning': 'بناء مستقبل أكثر إشراقاً من خلال التعلم',
    'Join us in providing quality education and literacy programs that empower communities to break the cycle of poverty and create sustainable change.': 'انضم إلينا في توفير تعليم عالي الجودة وبرامج محو الأمية التي تمكن المجتمعات من كسر دائرة الفقر وخلق تغيير مستدام.',
    'Support Education': 'دعم التعليم',
    'Bringing Medical Care to Those in Need': 'جلب الرعاية الطبية لمن يحتاجونها',
    'Help us expand access to essential healthcare services and health education in underserved communities worldwide.': 'ساعدنا في توسيع الوصول إلى الخدمات الصحية الأساسية والتثقيف الصحي في المجتمعات المحرومة في جميع أنحاء العالم.',
    'Support Healthcare': 'دعم الرعاية الصحية',
    'Environmental Conservation for Future Generations': 'الحفاظ على البيئة للأجيال القادمة',
    'Support our environmental conservation efforts and sustainable practices that preserve ecosystems while empowering local communities.': 'ادعم جهودنا للحفاظ على البيئة والممارسات المستدامة التي تحافظ على النظم البيئية بينما تمكن المجتمعات المحلية.',
    'Support Environment': 'دعم البيئة',
    'Clean Water for Life': 'مياه نظيفة للحياة',
    'Building Sustainable Water Systems': 'بناء أنظمة مياه مستدامة',
    'Help us provide clean, safe water access to communities in need through sustainable water systems and conservation education.': 'ساعدنا في توفير الوصول إلى المياه النظيفة والآمنة للمجتمعات المحتاجة من خلال أنظمة المياه المستدامة والتعليم على الحفاظ.',
    'Support Water Projects': 'دعم مشاريع المياه',
    'Discover how we\\'re creating sustainable change in communities worldwide': 'اكتشف كيف نخلق تغييراً مستداماً في المجتمعات في جميع أنحاء العالم',
  'Ready to Plant Seeds of Change?': 'هل أنت مستعد لزرع بذور التغيير؟',
    'Join our growing community of changemakers and help us nurture hope in communities that need it most. Every contribution, no matter the size, creates ripples of positive change.': 'انضم إلى مجتمعنا المتنامي من صانعي التغيير وساعدنا في رعاية الأمل في المجتمعات التي تحتاجه أكثر. كل مساهمة، بغض النظر عن حجمها، تخلق موجات من التغيير الإيجابي.',
    'Learn Our Story': 'تعرف على قصتنا',
    'We work across multiple interconnected areas to create comprehensive, sustainable change': 'نعمل عبر مجالات متعددة ومترابطة لخلق تغيير شامل ومستدام',
    'Implementing sustainable practices and conservation efforts to preserve ecosystems for future generations while empowering local communities.': 'تطبيق ممارسات مستدامة وجهود الحفاظ على النظم البيئية للأجيال القادمة بينما نمكن المجتمعات المحلية.',
    'Learn About Our Impact': 'تعرف على تأثيرنا',
    'Community Wellness': 'الصحة المجتمعية',
    'Providing essential healthcare services and health education to underserved communities, ensuring everyone has access to quality medical care.': 'توفير خدمات الرعاية الصحية الأساسية والتثقيف الصحي للمجتمعات المحرومة، مما يضمن حصول الجميع على رعاية طبية عالية الجودة.',
    'Like the mighty baobab tree, we believe in deep roots, strong growth, and lasting impact.': 'مثل شجرة الباوباب العظيمة، نؤمن بالجذور العميقة والنمو القوي والتأثير الدائم.',
    'Our Purpose': 'غرضنا',
    'To nurture sustainable growth in communities through education, empowerment, and environmental stewardship, creating lasting positive change that spans generations.': 'رعاية النمو المستدام في المجتمعات من خلال التعليم والتمكين والإشراف البيئي، وخلق تغيير إيجابي دائم يمتد عبر الأجيال.',
    'Since our founding in 2020, we have been committed to creating sustainable solutions that address the root causes of poverty, inequality, and environmental degradation.': 'منذ تأسيسنا في عام 2020، التزمنا بإنشاء حلول مستدامة تعالج الأسباب الجذرية للفقر وعدم المساواة والتدهور البيئي.',
    'What Drives Us': 'ما يدفعنا',
    'Our core values guide every decision we make and every action we take in service of our mission.': 'قيمنا الأساسية توجه كل قرار نتخذه وكل إجراء نتخذه في خدمة مهمتنا.',
    'We believe in nurturing long-term, sustainable solutions that grow stronger over time, just like the baobab tree.': 'نؤمن برعاية حلول طويلة الأجل ومستدامة تصبح أقوى بمرور الوقت، تماماً مثل شجرة الباوباب.',
    'Communities are at the heart of everything we do. We listen, learn, and work together to create meaningful change.': 'المجتمعات في قلب كل ما نقوم به. نستمع ونتعلم ونعمل معاً لخلق تغيير ذي مغزى.',
    'We maintain complete transparency in our operations, finances, and impact to build lasting trust with our supporters.': 'نحافظ على شفافية كاملة في عملياتنا وتمويلنا وتأثيرنا لبناء ثقة دائمة مع داعمينا.',
    'We empower individuals and communities with the tools, knowledge, and resources they need to thrive independently.': 'نمكن الأفراد والمجتمعات بالأدوات والمعرفة والموارد التي يحتاجونها للازدهار بشكل مستقل.',
    'Our Journey': 'رحلتنا',
    'Growing Together Since 2020': 'النمو معاً منذ 2020',
    'From humble beginnings to global impact, see how BAOBAB HOPE has grown and evolved.': 'من البدايات المتواضعة إلى التأثير العالمي، شاهد كيف نمت وتطورت BAOBAB HOPE.',
    'Started with a vision to create sustainable change': 'بدأت برؤية لخلق تغيير مستدام',
    '$25': '25$',
    '$50': '50$',
    'USD': 'USD',
    '${amount}': '${amount}',
    'gal': 'غالون'
};

console.log('Applying final translations to ES, IT, AR...');
translations.es = apply(translations.es, spanishFinal);
translations.it = apply(translations.it, italianFinal);
translations.ar = apply(translations.ar, arabicFinal);

fs.writeFileSync('./public/locales/translations.json', JSON.stringify(translations, null, 2), 'utf8');
console.log('✅ ALL LANGUAGES COMPLETE!');
